services:
  redis:
    image: 'redis:7.4-alpine'
    container_name: redis_test
    environment:
      - REDIS_PASSWORD=password
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
