# server config
server:
  port: 8000
  servlet:
    context-path: /api/v1

spring:
  application:
    name: spring-data-redis

  # db config
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  # jpa config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # h2 config
  h2:
    console:
      enabled: true
      path: /h2-console

  # redis config
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: REDIS
