server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: spring-boot-data-jpa

  # db config
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_data_jpa_test
    username: postgres
    password: postgres-pass-24
    driver-class-name: org.postgresql.Driver

  # jpa config
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        # Use implicit-strategy and physical-strategy for modern Spring/Hibernate
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Correct indentation for format_sql

  sql:
    init:
      mode: NEVER
      data-locations: classpath:db/data.sql