services:
  postgresql:
    image: postgres:17.6
    container_name: hospital_postgres
    # shared memory size for postgres
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - hospital_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  hospital_network:
    driver: bridge
volumes:
  postgres_data:
    driver: local